C AGDISPsetInputData
C Continuum Dynamics, Inc.
C SCIPUFF Implementation: 8.29 09/15/16
C
      SUBROUTINE AGDISPsetInputData(UD,IERT,FILEI)
C
C PURPOSE: load user model values into AGDSTRUC.INC
C
      CHARACTER*40 CMNT
      CHARACTER*128 FILEI
C
      INCLUDE 'AGDSTRUC.INC'
C
      RECORD /USERDATA/ UD
C
C Set a file name for input data
C
      NINU=4
      OPEN (NINU,FILE=FILEI,STATUS='old')
C
C AGDISP Container Data
C
      READ (NINU,1000) CMNT
      READ (NINU,*) IVERSION
      IF (IVERSION.NE.9) THEN
        IERT=-1
        RETURN
      ENDIF
C      READ (NINU,*) UD.TIER
      READ (NINU,*) UD.APPLMETH
      READ (NINU,*) AIRTYPE
C      READ (NINU,*) SMOKEY
      READ (NINU,1000) CMNT
      READ (NINU,*) ITEM
      READ (NINU,1000) CMNT
C
C  Ground Application Data
C
C      READ (NINU,*) UD.GA.BASICTYP
      READ (NINU,*) UD.GA.NUMSWATH
      READ (NINU,*) UD.GA.NOZTYPE
      READ (NINU,*) UD.GA.PRESSURE
C
C Orchard Airblast Application Data
C
C      READ (NINU,*) UD.OA.BASICTYP
C      READ (NINU,*) UD.OA.BEGTROW
C     READ (NINU,*) UD.OA.ENDTROW
C
C Drop Size Distribution Data
C
C      DO IDSD=1,3
        READ (NINU,*) UD.DSD.TYPE
        READ (NINU,*) UD.DSD.BASICTYP
        READ (NINU,1000) UD.DSD.NAME
        READ (NINU,*) UD.DSD.LNAME
        READ (NINU,*) UD.DSD.NUMDROP
        DO ND=1,UD.DSD.NUMDROP
          READ (NINU,*) UD.DSD.DIAM(ND),UD.DSD.MASSFRAC(ND)
        ENDDO
C        READ (NINU,*) UD.DSD.LIBFLAG
C      ENDDO
C
C USDA ARS Nozzle Models Data
C
C      DO IDSD=1,3
        READ (NINU,*) UD.BK.MXERRLV
        READ (NINU,*) UD.BK.NOZTYPE
        READ (NINU,1000) UD.BK.NAMENOZ
        READ (NINU,*) UD.BK.LNAMENOZ
C        READ (NINU,1000) UD.BK.NAMETYPE
C        READ (NINU,*) UD.BK.LNAMETYPE
        READ (NINU,*) UD.BK.ORIFICE
        READ (NINU,*) UD.BK.SPEED
        READ (NINU,*) UD.BK.NOZANGLE
        READ (NINU,*) UD.BK.PRESSURE
        READ (NINU,*) UD.BK.SPRTYPE
C        READ (NINU,*) UD.BK(IDSD).SPECSRC
C      ENDDO
C
C USDA FS Rotary Atomizer Models Data
C
C      DO IDSD=1,3
        READ (NINU,*) UD.HK.MXERRLV
        READ (NINU,*) UD.HK.MATTYPE
        READ (NINU,*) UD.HK.ROTTYPE
        READ (NINU,*) UD.HK.SPEED
        READ (NINU,*) UD.HK.BLADEANG
        READ (NINU,*) UD.HK.RPM
        READ (NINU,*) UD.HK.FLOWRATE
        READ (NINU,*) UD.HK.SPRTYPE
C      ENDDO
C
C Dropkick Data
C
C      DO IDSD=1,3
C        READ (NINU,*) UD.DK(IDSD).MXERRLV
C        READ (NINU,*) UD.DK(IDSD).NOZTYPE
C        READ (NINU,1000) UD.DK(IDSD).NAMENOZ
C        READ (NINU,*) UD.DK(IDSD).LNAMENOZ
C        READ (NINU,*) UD.DK(IDSD).VMD
C        READ (NINU,*) UD.DK(IDSD).RSPAN
C        READ (NINU,*) UD.DK(IDSD).EFFDIAM
C        READ (NINU,*) UD.DK(IDSD).SPRANGLE
C        READ (NINU,*) UD.DK(IDSD).MATTYPE
C        READ (NINU,1000) UD.DK(IDSD).NAMEMAT
C        READ (NINU,*) UD.DK(IDSD).LNAMEMAT
C        READ (NINU,*) UD.DK(IDSD).SURFTENS
C        READ (NINU,*) UD.DK(IDSD).SHEARVIS
C        READ (NINU,*) UD.DK(IDSD).DENSITY
C        READ (NINU,*) UD.DK(IDSD).ELONGVIS
C        READ (NINU,*) UD.DK(IDSD).SPEED
C        READ (NINU,*) UD.DK(IDSD).NOZANGLE
C        READ (NINU,*) UD.DK(IDSD).PRESSURE
C        READ (NINU,*) UD.DK(IDSD).FLOWFLAG
C        READ (NINU,*) UD.DK(IDSD).FLOW
C        READ (NINU,*) UD.DK(IDSD).SPRTYPE
C      ENDDO
C
C Spray Material Data
C
      READ (NINU,*) UD.SM.TYPE
      READ (NINU,*) UD.SM.BASICTYP
      READ (NINU,1000) UD.SM.NAME
      READ (NINU,*) UD.SM.LNAME
      READ (NINU,*) UD.SM.CALCINP
      READ (NINU,*) UD.SM.NVFRAC
      READ (NINU,*) UD.SM.ACFRAC
      READ (NINU,*) UD.SM.ACTSOLFR
      READ (NINU,*) UD.SM.ADDSOLFR
      READ (NINU,*) UD.SM.ACTNVFRA
      READ (NINU,*) UD.SM.ADDNVFRA
      READ (NINU,*) UD.SM.FLOWRATE
      READ (NINU,*) UD.SM.FLOWUNIT
      READ (NINU,*) UD.SM.SPECGRAV
      READ (NINU,*) UD.SM.NONVGRAV
      READ (NINU,*) UD.SM.EVAPRATE
C
C Aircraft Data
C
      READ (NINU,*) UD.AC.TYPE
C      READ (NINU,*) UD.AC.BASICTYP
      READ (NINU,1000) UD.AC.NAME
      READ (NINU,*) UD.AC.LNAME
      READ (NINU,*) UD.AC.WINGTYPE
      READ (NINU,*) UD.AC.SEMISPAN
      READ (NINU,*) UD.AC.TYPSPEED
      READ (NINU,*) UD.AC.BIPLSEP
      READ (NINU,*) UD.AC.WEIGHT
      READ (NINU,*) UD.AC.PLANAREA
      READ (NINU,*) UD.AC.PROPRPM
      READ (NINU,*) UD.AC.PROPRAD
      READ (NINU,*) UD.AC.PROPEFF
      READ (NINU,*) UD.AC.ENGVERT
      READ (NINU,*) UD.AC.ENGFWD
      READ (NINU,*) UD.AC.NUMENG
      READ (NINU,*) UD.AC.ENGHORIZ(1)
      READ (NINU,*) UD.AC.ENGHORIZ(2)
      READ (NINU,*) UD.AC.WINGVERT
      READ (NINU,*) UD.AC.BOOMVERT
      READ (NINU,*) UD.AC.BOOMFWD
      READ (NINU,*) UD.AC.DRAG
C
C Nozzle Data
C
      READ (NINU,*) UD.NZ.TYPE
C      READ (NINU,*) UD.NZ.BASICTYP  !ARE WE USING THIS VARIABLE
      READ (NINU,1000) UD.NZ.NAME
      READ (NINU,*) UD.NZ.LNAME
      READ (NINU,*) UD.NZ.NUMNOZ
      DO NN=1,UD.NZ.NUMNOZ
C        READ (NINU,*) UD.NZ.NOZTYP(NN),UD.NZ.POSHORIZ(NN),
        READ (NINU,*) UD.NZ.POSHORIZ(NN),
     $                UD.NZ.POSVERT(NN),UD.NZ.POSFWD(NN)
      ENDDO
      READ (NINU,*) UD.NZ.POSHLIMIT
      READ (NINU,*) UD.NZ.BOOMWIDTH
C
C Dry Deposition Data
C
      READ (NINU,*) UD.DRY.TYPE
      READ (NINU,*) UD.DRY.SPHERICITY
      READ (NINU,*) UD.DRY.WIDTH
      READ (NINU,*) UD.DRY.ANGLE
      READ (NINU,*) UD.DRY.VELOCITY
      READ (NINU,*) UD.DRY.HUB
      READ (NINU,*) UD.DRY.RPM
      READ (NINU,*) UD.DRY.LENGTH
C  
C Meteorological Data
C
      READ (NINU,*) UD.MET.WINDTYPE
      READ (NINU,*) UD.MET.NUMWINDT
      IF (UD.MET.WINDTYPE.EQ.1) THEN
        DO NW=1,UD.MET.NUMWINDT
          READ (NINU,*) UD.MET.WINDTWH(NW),UD.MET.WINDTWS(NW)
        ENDDO
      ENDIF
      READ (NINU,*) UD.MET.WINDSPD
      READ (NINU,*) UD.MET.WINDDIR
      READ (NINU,*) UD.MET.WINDHGT
      READ (NINU,*) UD.MET.TEMP
      READ (NINU,*) UD.MET.HUMIDITY
      READ (NINU,*) UD.MET.PRESSURE
      READ (NINU,*) UD.MET.VDECAYIG
      READ (NINU,*) UD.MET.VDECAYOG
      READ (NINU,*) UD.MET.SURFRUFF
      READ (NINU,*) UD.MET.INSOL
C
C Canopy Data
C
      READ (NINU,*) UD.CAN.TYPE
      READ (NINU,1000) UD.CAN.NAME
      READ (NINU,*) UD.CAN.LNAME
      READ (NINU,*) UD.CAN.ELESIZ
      READ (NINU,*) UD.CAN.ELETYP
      READ (NINU,*) UD.CAN.STANDEN
      READ (NINU,*) UD.CAN.NUMENV
      IF (UD.CAN.NUMENV.NE.0) THEN
        DO NC=1,UD.CAN.NUMENV
          READ (NINU,*) UD.CAN.ENVHGT(NC),UD.CAN.ENVDIA(NC),
     $                  UD.CAN.ENVPOP(NC)
        ENDDO
      ENDIF
      READ (NINU,*) UD.CAN.OPTYPE
      READ (NINU,*) UD.CAN.LIBHGT
      READ (NINU,*) UD.CAN.LIBLAI
      READ (NINU,*) UD.CAN.LIBB
      READ (NINU,*) UD.CAN.LIBC
      READ (NINU,*) UD.CAN.LIBQUAL
      READ (NINU,*) UD.CAN.NUMLAI
      IF (UD.CAN.NUMLAI.NE.0) THEN 
        DO NC=1,UD.CAN.NUMLAI
          READ (NINU,*) UD.CAN.LAIHGT(NC),UD.CAN.LAICUM(NC)
        ENDDO
      ENDIF
      READ (NINU,*) UD.CAN.TEMP
      READ (NINU,*) UD.CAN.HUMIDITY
      READ (NINU,*) UD.CAN.NDRUFF
      READ (NINU,*) UD.CAN.NDDISP
      READ (NINU,*) UD.CAN.HEIGHT
C
C Terrain Data
C
      READ (NINU,*) UD.TRN.ZREF
      READ (NINU,*) UD.TRN.UPSLOPE
      READ (NINU,*) UD.TRN.SIDESLOPE
C
C Control Data
C
      READ (NINU,*) UD.CTL.HEIGHT
      READ (NINU,*) UD.CTL.NUMLINES
      DO L=1,UD.CTL.NUMLINES
        READ (NINU,*) UD.CTL.LINEREPS(L)
      ENDDO
      READ (NINU,*) UD.CTL.LINEOPT
C      READ (NINU,*) UD.CTL.SWTYPE
      READ (NINU,*) UD.CTL.SWATHWID
C      READ (NINU,*) UD.CTL.SDTYPE
      READ (NINU,*) UD.CTL.SDVALUE
      READ (NINU,*) UD.CTL.SWATHOFF
      READ (NINU,*) UD.CTL.FLXPLANE
C      READ (NINU,*) UD.CTL.HGTRN
      READ (NINU,*) UD.CTL.MAXTIME
      READ (NINU,*) UD.CTL.MAXDWND
      READ (NINU,*) UD.CTL.HALFBOOM
      READ (NINU,*) UD.CTL.SAVETRAJ
C      READ (NINU,*) UD.CTL.ITSTWDIR
C      READ (NINU,*) UD.CALPUFFFLAG
      UD.CALPUFFFLAG=0
C
C SCIPUFF Flags
C
      UD.SCIPUFFFLAG=1
      UD.SCIPUFFCUTOFF=0.005
C
      CLOSE (NINU)
      RETURN
1000  FORMAT(A)
      END